fake_companies = [
    {
        "entity_urn": "urn:li:company:123456",
        "id": 1,
        "website": "www.example1.com",
        "customer_type": "B2B",
        "name": "Example Corp",
        "description": "A leading provider of innovative tech solutions.",
        "external_description": "Example Corp specializes in AI and automation.",
        "founding_date": "2010-06-15",
        "headcount": 250,
        "ownership_status": "Private",
        "company_type": "Tech",
        "stage": "Growth",
        "country": "United States",
        "funding_stage": "Series B",
        "funding_total": 25000000,
        "last_funding_at": "2022-05-10",
        "last_funding_total": 10000000,
        "last_funding_type": "Series B",
        "num_funding_rounds": 3,
        "highlights": ["Recognized as Top AI Innovator", "Fortune 500 Clients"],
        "funding_attribute_null_status": False,
        "traction_metrics": {"revenue": 1500000, "customer_growth": 0.3},
        "headcount_growth": 0.2,
    },
    {
        "entity_urn": "urn:li:company:654321",
        "id": 2,
        "website": "www.example2.com",
        "customer_type": "B2C",
        "name": "Innovate Ltd",
        "description": "Revolutionizing the e-commerce experience.",
        "external_description": "Innovate Ltd creates seamless online shopping tools.",
        "founding_date": "2015-03-22",
        "headcount": 120,
        "ownership_status": "Public",
        "company_type": "E-commerce",
        "stage": "Scale",
        "country": "Canada",
        "funding_stage": "Series C",
        "funding_total": 50000000,
        "last_funding_at": "2023-08-01",
        "last_funding_total": 20000000,
        "last_funding_type": "Series C",
        "num_funding_rounds": 4,
        "highlights": ["IPO planned for 2025", "Partnered with Shopify"],
        "funding_attribute_null_status": False,
        "traction_metrics": {"revenue": 2500000, "customer_growth": 0.5},
        "headcount_growth": 0.3,
    },
    {
        "entity_urn": "urn:li:company:789012",
        "id": 3,
        "website": "www.example3.com",
        "customer_type": "B2B",
        "name": "Green Energy Inc.",
        "description": "Pioneering renewable energy solutions.",
        "external_description": "Green Energy Inc. leads in solar and wind technologies.",
        "founding_date": "2008-11-11",
        "headcount": 500,
        "ownership_status": "Private",
        "company_type": "Renewable Energy",
        "stage": "Mature",
        "country": "Germany",
        "funding_stage": "Series D",
        "funding_total": 150000000,
        "last_funding_at": "2023-01-20",
        "last_funding_total": 50000000,
        "last_funding_type": "Series D",
        "num_funding_rounds": 5,
        "highlights": ["Top Clean Energy Innovator", "Deployed 10GW capacity worldwide"],
        "funding_attribute_null_status": False,
        "traction_metrics": {"revenue": 20000000, "customer_growth": 0.15},
        "headcount_growth": 0.1,
    },
    {
        "entity_urn": "urn:li:company:345678",
        "id": 4,
        "website": "www.example4.com",
        "customer_type": "B2C",
        "name": "Healthify",
        "description": "Empowering individuals with personalized health solutions.",
        "external_description": "Healthify offers AI-powered health tracking apps.",
        "founding_date": "2020-07-01",
        "headcount": 50,
        "ownership_status": "Startup",
        "company_type": "Health Tech",
        "stage": "Seed",
        "country": "United Kingdom",
        "funding_stage": "Seed",
        "funding_total": 3000000,
        "last_funding_at": "2022-10-15",
        "last_funding_total": 1500000,
        "last_funding_type": "Seed",
        "num_funding_rounds": 1,
        "highlights": ["Featured in TechCrunch", "500,000+ app downloads"],
        "funding_attribute_null_status": False,
        "traction_metrics": {"revenue": 300000, "customer_growth": 0.7},
        "headcount_growth": 0.5,
    }
]
