fake_companies = [
    {
        "entity_urn": "urn:li:company:123456",
        "id": 1,
        "website": "www.example1.com",
        "customer_type": "B2B",
        "name": "Example Corp",
        "description": "A leading provider of innovative tech solutions.",
        "external_description": "Example Corp specializes in AI and automation.",
        "founding_date": "2010-06-15",
        "headcount": 250,
        "ownership_status": "Private",
        "company_type": "Tech",
        "stage": "Growth",
        "country": "United States",
        "funding_stage": "Series B",
        "funding_total": 25000000,
        "last_funding_at": "2022-05-10",
        "last_funding_total": 10000000,
        "last_funding_type": "Series B",
        "num_funding_rounds": 3,
        "highlights": ["Recognized as Top AI Innovator", "Fortune 500 Clients"],
        "funding_attribute_null_status": False,
        "traction_metrics": {"revenue": 1500000, "customer_growth": 0.3},
        "headcount_growth": 0.2,
    },
    {
        "entity_urn": "urn:li:company:654321",
        "id": 2,
        "website": "www.example2.com",
        "customer_type": "B2C",
        "name": "Innovate Ltd",
        "description": "Revolutionizing the e-commerce experience.",
        "external_description": "Innovate Ltd creates seamless online shopping tools.",
        "founding_date": "2015-03-22",
        "headcount": 120,
        "ownership_status": "Public",
        "company_type": "E-commerce",
        "stage": "Scale",
        "country": "Canada",
        "funding_stage": "Series C",
        "funding_total": 50000000,
        "last_funding_at": "2023-08-01",
        "last_funding_total": 20000000,
        "last_funding_type": "Series C",
        "num_funding_rounds": 4,
        "highlights": ["IPO planned for 2025", "Partnered with Shopify"],
        "funding_attribute_null_status": False,
        "traction_metrics": {"revenue": 2500000, "customer_growth": 0.5},
        "headcount_growth": 0.3,
    },
    {
        "entity_urn": "urn:li:company:789012",
        "id": 3,
        "website": "www.example3.com",
        "customer_type": "B2B",
        "name": "Green Energy Inc.",
        "description": "Pioneering renewable energy solutions.",
        "external_description": "Green Energy Inc. leads in solar and wind technologies.",
        "founding_date": "2008-11-11",
        "headcount": 500,
        "ownership_status": "Private",
        "company_type": "Renewable Energy",
        "stage": "Mature",
        "country": "Germany",
        "funding_stage": "Series D",
        "funding_total": 150000000,
        "last_funding_at": "2023-01-20",
        "last_funding_total": 50000000,
        "last_funding_type": "Series D",
        "num_funding_rounds": 5,
        "highlights": ["Top Clean Energy Innovator", "Deployed 10GW capacity worldwide"],
        "funding_attribute_null_status": False,
        "traction_metrics": {"revenue": 20000000, "customer_growth": 0.15},
        "headcount_growth": 0.1,
    },
    {
        "entity_urn": "urn:li:company:345678",
        "id": 4,
        "website": "www.example4.com",
        "customer_type": "B2C",
        "name": "Healthify",
        "description": "Empowering individuals with personalized health solutions.",
        "external_description": "Healthify offers AI-powered health tracking apps.",
        "founding_date": "2020-07-01",
        "headcount": 50,
        "ownership_status": "Startup",
        "company_type": "Health Tech",
        "stage": "Seed",
        "country": "United Kingdom",
        "funding_stage": "Seed",
        "funding_total": 3000000,
        "last_funding_at": "2022-10-15",
        "last_funding_total": 1500000,
        "last_funding_type": "Seed",
        "num_funding_rounds": 1,
        "highlights": ["Featured in TechCrunch", "500,000+ app downloads"],
        "funding_attribute_null_status": False,
        "traction_metrics": {"revenue": 300000, "customer_growth": 0.7},
        "headcount_growth": 0.5,
    },
    {
        "entity_urn": "urn:li:company:123457",
        "id": 5,
        "website": "www.cloudzone.com",
        "customer_type": "B2B",
        "name": "CloudZone",
        "description": "Cloud infrastructure for modern enterprises.",
        "external_description": "CloudZone offers scalable cloud solutions for businesses.",
        "founding_date": "2012-04-10",
        "headcount": 350,
        "ownership_status": "Private",
        "company_type": "Cloud Computing",
        "stage": "Growth",
        "country": "United States",
        "funding_stage": "Series C",
        "funding_total": 75000000,
        "last_funding_at": "2022-11-15",
        "last_funding_total": 30000000,
        "last_funding_type": "Series C",
        "num_funding_rounds": 4,
        "highlights": ["Partnered with AWS", "100+ Fortune 500 clients"],
        "funding_attribute_null_status": False,
        "traction_metrics": {"revenue": 12000000, "customer_growth": 0.4},
        "headcount_growth": 0.15
    },
    {
        "entity_urn": "urn:li:company:654322",
        "id": 6,
        "website": "www.agritechsolutions.com",
        "customer_type": "B2B",
        "name": "AgriTech Solutions",
        "description": "Smart farming technology for sustainable agriculture.",
        "external_description": "Empowering farmers with AI and IoT for better yields.",
        "founding_date": "2018-09-05",
        "headcount": 100,
        "ownership_status": "Private",
        "company_type": "Agriculture Tech",
        "stage": "Series A",
        "country": "India",
        "funding_stage": "Series A",
        "funding_total": 8000000,
        "last_funding_at": "2023-03-10",
        "last_funding_total": 5000000,
        "last_funding_type": "Series A",
        "num_funding_rounds": 2,
        "highlights": ["Deployed in 15 countries", "Recognized for AI innovations in agriculture"],
        "funding_attribute_null_status": False,
        "traction_metrics": {"revenue": 1500000, "customer_growth": 0.6},
        "headcount_growth": 0.25
    },
    {
        "entity_urn": "urn:li:company:789013",
        "id": 7,
        "website": "www.neuralnexus.com",
        "customer_type": "B2B",
        "name": "Neural Nexus",
        "description": "AI-powered data analytics platform for enterprises.",
        "external_description": "Transforming raw data into actionable insights.",
        "founding_date": "2017-01-20",
        "headcount": 200,
        "ownership_status": "Private",
        "company_type": "AI/Analytics",
        "stage": "Series B",
        "country": "Canada",
        "funding_stage": "Series B",
        "funding_total": 30000000,
        "last_funding_at": "2021-09-15",
        "last_funding_total": 15000000,
        "last_funding_type": "Series B",
        "num_funding_rounds": 3,
        "highlights": ["Top AI startup in North America", "2 million API calls daily"],
        "funding_attribute_null_status": False,
        "traction_metrics": {"revenue": 8000000, "customer_growth": 0.3},
        "headcount_growth": 0.2
    },
    {
        "entity_urn": "urn:li:company:345679",
        "id": 8,
        "website": "www.biomedinnovators.com",
        "customer_type": "B2B",
        "name": "BioMed Innovators",
        "description": "Pioneering biotech solutions for healthcare.",
        "external_description": "Leading the charge in innovative biomedical research.",
        "founding_date": "2010-02-14",
        "headcount": 400,
        "ownership_status": "Public",
        "company_type": "Biotech",
        "stage": "Mature",
        "country": "Switzerland",
        "funding_stage": "IPO",
        "funding_total": 250000000,
        "last_funding_at": "2020-01-10",
        "last_funding_total": 75000000,
        "last_funding_type": "IPO",
        "num_funding_rounds": 5,
        "highlights": ["Developed 3 FDA-approved drugs", "Listed on Swiss Stock Exchange"],
        "funding_attribute_null_status": False,
        "traction_metrics": {"revenue": 35000000, "customer_growth": 0.1},
        "headcount_growth": 0.05
    },
    {
        "entity_urn": "urn:li:company:987654",
        "id": 9,
        "website": "www.sustainify.com",
        "customer_type": "B2C",
        "name": "Sustainify",
        "description": "Eco-friendly products for a sustainable future.",
        "external_description": "Shop for planet-friendly goods.",
        "founding_date": "2021-05-18",
        "headcount": 30,
        "ownership_status": "Startup",
        "company_type": "E-commerce",
        "stage": "Seed",
        "country": "Australia",
        "funding_stage": "Seed",
        "funding_total": 2000000,
        "last_funding_at": "2022-12-01",
        "last_funding_total": 2000000,
        "last_funding_type": "Seed",
        "num_funding_rounds": 1,
        "highlights": ["Carbon-neutral supply chain", "Featured in Forbes Green Tech"],
        "funding_attribute_null_status": False,
        "traction_metrics": {"revenue": 150000, "customer_growth": 0.8},
        "headcount_growth": 0.6
    }
]
